### PR TITLE
fix: prevent overwriting htmlAttributes.ref

### LINKED ISSUE #494: htmlAttributes ref function not called
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
Since the 9.0 release, `ref` functions passed via `htmlAttributes` are no longer working.

**To Reproduce**

```js
const handleRef = img => {
  // this should be called after the img is rendered in the DOM
}

return (
  <Imgix
    ...
    htmlAttributes={{ ref: handleRef }}
  />
}
```

**Expected behaviour**
As per the docs, the ref function passed in `htmlAttributes` should be called after the image is loaded in the DOM with a reference to the image html element. 

**Information:**

- react-imgix version: v9.0
- I saw there was some work on ref handling for this release so I'm hoping this is straightforward to diagnose, but if not I can try to set up a repro. Thanks!

### PR DESCRIPTION
**Pull request by sherwinski**
Fixes #494 
Refactoring work completed in #475 inadvertently introduced a regression where we are overwriting a `ref` passed via `htmlAttributes`. This PR better handles this situation while accounting for refs that are either passed as a callback or an object.

### CODE REVIEW

**Comment by sherwinski** [comment]
@jaredloson Feel free to take a look and leave feedback as well.

File: src/react-imgix.jsx [hunk 1]
```diff
@@ -220,14 +220,20 @@ class ReactImgix extends Component {
...
+      {
+        [attributeConfig.sizes]: this.props.sizes,
+        className: this.props.className,
+        width: width <= 1 ? null : width,
+        height: height <= 1 ? null : height,
+        [attributeConfig.src]: src,
+        ref: el => {
+          this.imgRef = el;
+        }
+      },
```
Comment (sherwinski) [inline src/react-imgix.jsx]: The downside to this is that users could potentially overwrite any of the other properties included in this object blob via `htmlAttributes` if not careful. To prevent this, we could keep the original order but pull out the `ref` assignment before `htmlAttributes`. Thoughts?

File: test/unit/react-imgix.test.jsx [hunk 2]
```diff
@@ -166,6 +166,7 @@ describe("When in image mode", () => {
       />
     );
 
+    expect(onMountedSpy.called);
```
Comment (frederickfogerty) [inline test/unit/react-imgix.test.jsx]: This is a redundant assertion.

File: test/unit/react-imgix.test.jsx [hunk 3]
```diff
@@ -309,6 +310,56 @@ describe("When in <source> mode", () => {
...
+          htmlAttributes={htmlAttributes}
+        />
+      );
+
+      expect(sut.props()["htmlAttributes"]["data-src"]).toEqual(
+        htmlAttributes["data-src"]
+      );
+    });
+
+    it("attaches a ref via htmlAttributes", () => {
```
Comment (frederickfogerty) [inline test/unit/react-imgix.test.jsx]: We should add a test here for when `htmlAttributes.ref` is used, that onMounted is also called.

File: src/react-imgix.jsx (hunk 1 above)
Comment (frederickfogerty) [reply src/react-imgix.jsx]: For problems like these I like to go with the second option you suggested.

File: src/react-imgix.jsx [hunk 4]
```diff
@@ -220,14 +220,20 @@ class ReactImgix extends Component {
...
+      this.props.htmlAttributes
+    );
```
Comment (frederickfogerty) [inline src/react-imgix.jsx]: I'm going to go out on a limb here and say that this is not the change we want. The problem here is that our own internal ref is not set when someone overrides the ref.

Instead, I think we should combine the ref handler into one handler. Something like this:

```jsx
ref: el => {
  this.imgRef = el; // handle internal ref
  
  setParentRef(this.props.htmlAttributes.ref); // handle ref from htmlAttributes
}

// elsewhere
const setParentRef = (ref) => {
  if (!ref) { return }

  // callback refs
  if (typeof ref === 'function') {
    ref(element);
  }

  // "modern" refs
  ref.current = element;
}
```

`setParentRef` needs to be a function that will handle `undefined`, and refs in the legacy and modern styles. You can find some more information on this, and various implementations, here: https://github.com/facebook/react/issues/13029. Be wary not to use hooks as that would violate our React version support range.

This package could also be useful: https://www.npmjs.com/package/@seznam/compose-react-refs

Comment (sherwinski) [reply src/react-imgix.jsx]: Awesome thanks. If I understood your points correctly, I think it should now be able to account for each of these cases. Give it another look over and let me know.

File: src/react-imgix.jsx [hunk 5]
```diff
@@ -331,12 +351,32 @@ class SourceImpl extends Component {
...
+        return;
+      }
+
+      // assign ref based on if it's a callback vs object
+      if (typeof ref === "function") {
+        ref(this.sourceRef);
+      } else {
+        ref.current = this.sourceRef;
+      }
+    };
```
Comment (frederickfogerty) [inline src/react-imgix.jsx]: I think we could keep this code more DRY and performant by making the signature `const setParentRef = (parentRef, el) =>` so that we don't have to redefine it in every render method

File: test/unit/react-imgix.test.jsx [hunk 6]
```diff
@@ -309,6 +309,75 @@ describe("When in <source> mode", () => {
...
+          sizes="100vw"
+          onMounted={onMountedCallback}
+          htmlAttributes={{ ref: htmlAttrCallback }}
+        />
+      );
+
+      expect(htmlAttrCallback.called).toBeTruthy();
+      expect(htmlAttrCallback.callCount).toEqual(1);
+      expect(onMountedCallback.called).toBeTruthy();
+      expect(onMountedCallback.callCount).toEqual(1);
```
Comment (frederickfogerty) [inline test/unit/react-imgix.test.jsx]: nit: `called` and `callCount` are overlapping assertions - we can just drop the `.called` assertion as the `.callCount` tests for the same thing.

File: test/unit/react-imgix.test.jsx [hunk 7]
```diff
@@ -309,6 +309,75 @@ describe("When in <source> mode", () => {
...
+      sut = mount(
+        <Source
+          src={"https://mysource.imgix.net/demo.png"}
+          sizes="100vw"
+          htmlAttributes={{ ref: callback }}
+        />
+      );
+
+      expect(callback.called).toBeTruthy();
+      expect(callback.callCount).toEqual(1);
```
Comment (frederickfogerty) [inline test/unit/react-imgix.test.jsx]: nit: same comment as below

File: test/unit/react-imgix.test.jsx (hunk 6 above)
Comment (sherwinski) [reply test/unit/react-imgix.test.jsx]: Ah forgot to take those out. Thanks
